project:
  render:
    - manuscript/manuscript.qmd
title: "Using Automatic Item Selection in Multi-Informant Assessment of Child Mental Health"
mainfont: "TeX Gyre Pagella"
floatsintext: true
csl: apa.csl
author:
  - name: Jan Luca Schnatz
    corresponding: true
    orcid: 0009-0004-3079-2317
    email: s2787063@stud.uni-frankfurt.de
    affiliations:
      - id: id1
        name: "Goethe University"
        group: Department of Psychological Methods with Interdisciplinary Focus
        department: Institute of Psychology
        address: "Theodor-W.-Adorno-Platz 1, 660323 Frankfurt am Main"
        city: Frankfurt
        region: Hessen
        country: Deutschland
        postal-code: 60323
blank-lines-above-author-note: 4
author-note:
  disclosures:
    study-registration: This work was preregistered on October 1st, 2025 on OSF (osf.io/hzus8).
    data-sharing:  The codebase for this study is publicly available on GitHub (https://github.com/jlschnatz/multi-informant-aseba). 
    conflict-of-interest: The authors have no conflicts of interest to disclose.
abstract: |
  | "Comprehensive clinical assessment of mental health in children and adolescents often relies on multiple informants, such as parents, teachers and children themselves. However, discrepancies in reports from different raters are common, leading to challenges in interpreting the results of assessment procedures. These discrepancies may arise because some items capture behaviors that are commonly observed across informants, while others reflect informant-specific perspectives unique to each rater. At the same time, there is a need for economic instruments that reduce burden for respondents and clinicians while maintaining reliability and validity. To address these challenges the present study aims to develop a subtest containing 32 items of the commonly employed multi-informant assessment instrument Achenbach System of Empirically Based Assessment (ASEBA) that balances shared and informant-specific perspectives while retaining a manageable number of items for economic admin- istration in clinical settings. This will be achieved within a structural equation modeling framework leveraging an automatic item selection approach to identify an item set that optimally satisfies a predefined set of construction criteria. The present study will use two waves of data of parent and child ratings on the ASEBA Child Behavior Checklist (CBCL/6-18) and Youth Self Report (YSR/11-18) from the SAFE children study (Tolan et al., 2016), a longitudinal randomized controlled trial with _N_ = 424 children and their primary caregivers that participated in a family-centered preventive intervention program"

keywords: 
  - Multi-Informant Assessment
  - Automatic Item Selection
  - Scale Construction
  - Achenbach System of Empirically Based Assessment

first-page: 1
bibliography: bibliography.bib
link-citations: true
draft-date: March 13, 2026
lang: en
language:
  citation-last-author-separator: "and"
  citation-masked-author: "Masked Citation"
  citation-masked-date: "n.d."
  citation-masked-title: "Masked Title"
  email: "Email"
  title-block-author-note: "Author Note"
  title-block-correspondence-note: "Correspondence concerning this article should be addressed to"
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; [credit.niso.org](https://credit.niso.org)) as follows:"
  title-impact-statement: "Impact Statement"
  references-meta-analysis: "References marked with an asterisk indicate studies included in the meta-analysis."
no-ampersand-parenthetical: false
fontsize: 11pt
linkcolor: black
format:
  apaquarto-typst:
    keep-typ: true
    blank-lines-above-author-note: 10
    list-of-figures: false
    list-of-tables: false
    toc: false
    papersize: "a4"
    numbering: false
    suppress-short-title: true
    suppress-corresponding-paragraph: true
