---
format: gfm
---


<!-- badges: start -->
<!-- badges: end -->

# Forschungsmodul *PsyMSc5*

## General Information

<table>
  <tr>
    <td><h5>Project Title</h5></td>
    <td><h5>Student</h5></td>
    <td><h5>Coordination</h5></td>
    <td><h5>Semester</h5></td>
  </tr>
  <tr>
    <td>Using Automatic Item Selection in Multi-Informant Assessment of Child Mental Health</td>
    <td>Luca Schnatz</td>
    <td>Prof. Martin Schultze</td>
    <td>SS25 + WS25/26</td>
  </tr>
  <tr>
    <td colspan="4">
      <h5>Abstract</h5>
      <p>Comprehensive clinical assessment of mental health in children and adolescents often relies on multiple informants, such as parents, teachers and children themselves. However, discrepancies in reports from different raters are common, leading to challenges in interpreting the results of assessment procedures. These discrepancies may arise because some items capture behaviors that are commonly observed across informants, while others reflect informant-specific perspectives unique to each rater. At the same time, there is a need for economic instruments that reduce burden for respondents and clinicians while maintaining reliability and validity. To address these challenges the present study aims to develop a subtest containing 32 items of the commonly employed multi-informant assessment instrument Achenbach System of Empirically Based Assessment (ASEBA) that balances shared and informant-specific perspectives while retaining a manageable number of items for economic administration in clinical settings. This will be achieved within a structural equation modeling framework leveraging an automatic item selection approach to identify an item set that optimally satisfies a predefined set of construction criteria. The present study will use two waves of data of parent and child ratings on the ASEBA Child Behavior Checklist (CBCL/6-18) and Youth Self Report (YSR/11-18) from the SAFE children study (Tolan et al., 2016), a longitudinal randomized controlled trial with N = 424 children and their primary caregivers that participated in a family-centered preventive intervention program.</p>
    </td>
  </tr>
</table>

## License

The code in the repository is licensed under the [GPL-3.0 License](https://www.gnu.org/licenses/gpl-3.0.de.html).

## Preregistration

The preregistration for this project was submitted on October, 1st, 2025 and can be found in the folder `preregistration/preregistration.pdf`. The OSF preregistration page can be found on [https://doi.org/10.17605/OSF.IO/FERJ5](https://doi.org/10.17605/OSF.IO/FERJ5).

## Data Download

Data used for this study is sourced from the Schools and Families Educating (SAFE) Children Study [ICPSR 34368], see https://doi.org/10.3886/ICPSR34368.v1. Data must not be redistributed on this platformaccording to the data use agreement but may be downloaded from the original source. To download the data, please register using an institutional email address and agree to the terms of the data use agreement. After registration, you can download the data directly from the [ICPSR website](https://www.icpsr.umich.edu/web/ICPSR/studies/34368). For reproducibility purposes, we recommend downloading the data as SAV (SPSS) files.

## Reproducibility of Project



### Dependecy Graph of targets

Test



```{r}
#| echo: false

library(targets)
merm <- tar_mermaid(reporter = "silent")
writeLines(merm, "mermaid.mmd")
```



```{mermaid}
%%| file:  mermaid.mmd
```




